// ============================================================
// ASSET CONFIG for properties.html (Vacant Land & NestFlex Builds)
// Generated by asset-manager.html
// ============================================================
window.ASSETS = {

  land: {
    photos: [
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/15-riebeek-street-seaview/01-last-elevated-vacant-stand-with-ocean-views-at-15-riebeeck-street-seaview-for-sale.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/15-riebeek-street-seaview/02-spectacular-sunset-ocean-views-15-riebeeck-street-seaview-gqeberha.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/15-riebeek-street-seaview/04-sea-waves-framed-by-coastal-flora-15-riebeeck-street-seaview.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/15-riebeek-street-seaview/05-dramatic-sunset-coastal-sky-seaview-port-elizabeth.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/15-riebeek-street-seaview/06-lush-coastal-vegetation-vacant-plot-seaview-clarendon-marine.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/15-riebeek-street-seaview/07-indigenous-coastal-ground-cover-15-riebeeck-street-clarendon-marine.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/15-riebeek-street-seaview/08-serene-sea-sunset-silhouettes-seaview-port-elizabeth.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/15-riebeek-street-seaview/03-elevated-vacant-stand-sloping-terrain-and-ocean-outlooks-seaview.jpg"
    ],
    videoTour: "",
    model3D: "https://3dviewer.co/share/4Rk0SG1QPj"
  },

  build: {
    floorPlan: "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/product-plan/5/5pln-con-1b-36.png",
    photos: [
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-1.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-2.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-3.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-4.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-5.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-6.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-7.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-8.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-9.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-10.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-11.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-12.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-13.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-14.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-15.jpg",
      "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/con-1bed-1bath/com-1b-16.jpg"
    ]
  },

  agent: {
    headshot: "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/General%20Profiles/headshot%20jlg.png",
    coverPhoto: "https://jmztkqukornrftdbeyto.supabase.co/storage/v1/object/public/oracle-portfolio/CurrentProject/WhatsApp%20Image%202026-06-28%20at%2018.23.46.jpeg"
  },

  portals: {
    property24: "https://www.property24.com/for-sale/seaview/gqeberha/eastern-cape/6945/117595371",
    privateProperty: "https://www.privateproperty.co.za/for-sale/eastern-cape/nelson-mandela-bay/port-elizabeth-gqeberha/seaview/clarendon-marine/15-riebeeck-street/T5612203",
    onlyRealty: "https://www.onlyrealty.co.za/results/residential/for-sale/gqeberha/seaview/vacant-land/3437221/15-riebeeck-street/"
  }

};
